services:
  gateway-svc:
    build:
      context: ./gateway-svc
      dockerfile: /Dockerfile
    container_name: gateway-svc
    environment:
      - USER_SERVICE_URL=http://user-svc:8081/user-svc
      - CHAT_SERVICE_URL=http://chat-svc:8082/chat-svc
      - MESSAGE_SERVICE_URL=http://message-svc:8083/message-svc
    ports:
      - "8080:8080"

  user-svc:
    build:
      context: .
      dockerfile: ./user-svc/Dockerfile
    container_name: user-svc
    environment:
      - DB_HOST=postgresql_database
    ports:
      - "8081:8081"

  chat-svc:
    build:
      context: .
      dockerfile: ./chat-svc/Dockerfile
    container_name: chat-svc
    environment:
      - DB_HOST=postgresql_database
      - USER_SERVICE_URL=http://user-svc:8081/user-svc/
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8082:8082"

  message-svc:
    build:
      context: .
      dockerfile: ./message-svc/Dockerfile
    container_name: message-svc
    environment:
      - USER_SERVICE_URL=http://user-svc:8081/user-svc/
      - SPRING_CASSANDRA_CONTACT-POINTS=scylla
      - CHAT_SERVICE_URL=http://chat-svc:8082/chat-svc/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_CASSANDRA_SCHEMA-ACTION=RECREATE
    ports:
      - "8083:8083"

  postgresql_database:
    image: postgres:17.4
    container_name: postgresql_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social_db
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  scylla:
    image: bitnami/scylladb:6.2.3
    container_name: scylla_db
    restart: always
    ports:
      - "7000:7000"
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla
      - ./init/scylla:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "redis_password" ]
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
      - "15674:15674"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    volumes:
      - ./init/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./init/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./init/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

volumes:
  redis_data:
    driver: local
  scylla_data:
    driver: local