server.port=8080
spring.application.name=gateway-service
user.service.url=http://localhost:8081/user-svc
chat.service.url=http://localhost:8082/chat-svc
message.service.url=http://localhost:8083/message-svc
jwt.secret=long_and_secure_jwt_secret_for_development
jwt.expiration=3600000
logging.level.root=INFO
monitoring.host=localhost
management.otlp.metrics.export.url=http://${monitoring.host}:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://${monitoring.host}:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://${monitoring.host}:4318/v1/logs
#for development
management.tracing.sampling.probability=1.0