server.port=8082
spring.application.name=chat-svc
server.servlet.context-path=/chat-svc/
# Database configuration
db.host=localhost
db.port=5432
db.user=postgres
db.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${db.host}:${db.port}/social_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=chat_schema
# Http configuration
spring.http.clients.connect-timeout=1s
spring.http.clients.read-timeout=10s
# rabbitmq configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=rabbit
spring.rabbitmq.virtual-host=my_vhost
# App configuration
user.service.url=http://localhost:8081/user-svc/
chat.events.queue.rabbit=chat_events_queue
message.events.queue.rabbit=message_events_queue
outbox.publisher.delay-ms=1000
outbox.publisher.batch-size=50
default.chat.page.size=20
spring.jpa.show-sql=false
# Liquibase configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=chat_schema
spring.liquibase.contexts=development
# Logging
logging.level.root=INFO
logging.level.org.zalando.logbook.Logbook=TRACE
# Monitoring configuration
monitoring.host=localhost
management.otlp.metrics.export.url=http://${monitoring.host}:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://${monitoring.host}:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://${monitoring.host}:4318/v1/logs
#for development
management.tracing.sampling.probability=1.0